### ISSUE TITLE
Anbox support

### ISSUE THREAD

**Issue by averyanalex** [HougeLangley/Xanmod-CaCule-UKSM#17]
Maybe add ashmem and binderfs to default config for anbox support?

**Comment by HougeLangley** [comment]
> Maybe add ashmem and binderfs to default config for anbox support?

Could you PR?

**Comment by averyanalex** [comment]
Now I don't know how to modify kernel configs automatically

**Comment by bigshans** [comment]
Or you can refer to linux-xanmod-anbox, but the version still stays at 5.12.

**Comment by bigshans** [comment]
@averyanalex You can configure anbox kernel support now.
