### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by bigshans** [HougeLangley/Xanmod-CaCule-UKSM#3]
I tried many times, and always failed to compile the sound module.

**Comment by HougeLangley** [comment]
> I tried many times, and always failed to compile the sound module.

Hi, could you give me ayn detail or log?

**Comment by bigshans** [comment]
> > I tried many times, and always failed to compile the sound module.
> 
> Hi, could you give me ayn detail or log?

I added the -j option. The final success should be related to the -j option.
