### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by bigshans** [HougeLangley/Xanmod-CaCule-UKSM#5]
```
==> Building this package for microarchitecture: CONFIG_MNATIVE

  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
  YACC    scripts/kconfig/parser.tab.[ch]
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
#
# configuration written to .config
#
  -> Prepared linux-xanmod-cacule-uksm version 5.11.15-xanmod1-cacule-1-cacule-uksm
  UPD     scripts/kconfig/nconf-cfg
  HOSTCC  scripts/kconfig/nconf.o
  HOSTCC  scripts/kconfig/nconf.gui.o
  HOSTLD  scripts/kconfig/nconf
Your terminal should have at least 20 lines and 75 columns
make[1]: *** [scripts/kconfig/Makefile:35：nconfig] 错误 1
make: *** [Makefile:602：nconfig] 错误 2
==> 错误： 在 prepare() 中发生一个错误。
    正在放弃...
```
Crashed from start.

**Comment by HougeLangley** [comment]
Hi, using AUR?

**Comment by HougeLangley** [comment]
Hi, I testing AUR is working great, have a try after clean build cache

**Comment by bigshans** [comment]
I cloned aur again but still crash. I'm using auracle.

**Comment by bigshans** [comment]
It's broken by yay too.

**Comment by bigshans** [comment]
My kernal version is v5.11.13-1 of linux-xanmod-cacule-uksm.

**Comment by bigshans** [comment]
```
patching file virt/kvm/kvm_main.c
```
Can't patch kvm.

**Comment by bigshans** [comment]
I passed linux-xanmod-cacule. I guess it maybe uksm problem.

**Comment by HougeLangley** [comment]
> My kernal version is v5.11.13-1 of linux-xanmod-cacule-uksm.

Oh, I guess you using this PKGBUILD file in github. Try `yay -S linux-xanmod-cacule-uksm linux-xanmod-cacule-uksm-headers`

**Comment by HougeLangley** [comment]
Clean cache and rebuild

**Comment by bigshans** [comment]
> > My kernal version is v5.11.13-1 of linux-xanmod-cacule-uksm.
> 
> Oh, I guess you using this PKGBUILD file in github. Try `yay -S linux-xanmod-cacule-uksm linux-xanmod-cacule-uksm-headers`
 
I tried too. It threw the same error.

**Comment by HougeLangley** [comment]
> > > My kernal version is v5.11.13-1 of linux-xanmod-cacule-uksm.
> > 
> > Oh, I guess you using this PKGBUILD file in github. Try `yay -S linux-xanmod-cacule-uksm linux-xanmod-cacule-uksm-headers`
>  
> I tried too. It threw the same error.
> 

I got it, full screen your terminal

**Comment by bigshans** [comment]
Wired, I build success when I under linux-xanmod-cacule. Problem maybe solved, thanks!
