### ISSUE TITLE
makepkg -si abort

### ISSUE THREAD

**Issue by lyjdwh** [HougeLangley/Xanmod-CaCule-UKSM#8]
![image](https://user-images.githubusercontent.com/14898811/120205789-f1890280-c25c-11eb-8b74-3d2ac481ec20.png)

**Comment by lyjdwh** [comment]
After I set the hostname in config interface, the problem solved.

I recommend setting a default hostname in the configuration so that it can be compiled successfully without additional settings

**Comment by HougeLangley** [comment]
Sorry, you could try makepkg -Ccsi

**Comment by lyjdwh** [comment]
I cleaned it up manually, but if I don’t set the hostname, I still get this error
