### ISSUE TITLE
linux-xanmod-cacule-uksm-headers build failed

### ISSUE THREAD

**Issue by bigshans** [HougeLangley/Xanmod-CaCule-UKSM#9]
tips: install: 无法获取'version' 的文件状态(stat): 没有那个文件或目录

**Comment by HougeLangley** [comment]
不好意思，我还没有来得及修 bug

**Comment by HougeLangley** [comment]
我或许会在这段时间慢慢修一下～

**Comment by bigshans** [comment]
其实可以开一个开发分支做的，完成了合并回主分支。 @HougeLangley

**Comment by HougeLangley** [comment]
其实我后续抄下aur那边的原版，只是最近我在弄gentoo的ebuild，另外也没用Arch了就一直耽搁着
